spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
#    password: root
    password: root
  web:
    resources:
      static-locations: classpath:/static/,file:${upload-path}
mybatis-plus:
  mapper-locations: classpath:com/example/tavern/mapper/xml/*.xml
